### PR TITLE
Refactor the core of the app using SwiftUI

### PR DESCRIPTION
**Pull request by anli5005**
The long-awaited refactor of our app in SwiftUI is here.

New home screen

Note that this PR updates the minimum deployment target to iOS 16.0.

Some tasks that I've deferred until later PRs:
* Rewriting the PAC code tab in SwiftUI (as that relies on navigation bar controls)
* ~~Fixing a rare crash when switching to the GSR/laundry tabs after re-pinning them to the tab bar (those are also related to navigation bar controls)~~ *now fixed!*
* Deleting now-unused code
* Refactoring the "Edit Features" screen to use the new `AppFeature` structs
* Tweaking the home screen with feedback from design

### CODE REVIEW

**Comment by george-botros** [comment]
Should the feature icons be white on light mode?

**Review by JHawk0224 — APPROVED** [review]
I think this is ready to be merged!

**Comment by george-botros** [comment]
Btw, aesthetics of poll history page is inconsistent with aesthetics of a poll on the homepage

simulator_screenshot_5D1D4774-7FAF-4110-BDC5-6DF97073E28B

**Comment by JHawk0224** [comment]
We should also remove the debug button

**Comment by JHawk0224** [comment]
> Btw, aesthetics of poll history page is inconsistent with aesthetics of a poll on the homepage
> 

fixed on mass-deletion branch

**Pull request merged**
