### PR TITLE
Home Page Reservations Cell

### PR DESCRIPTION
**Pull request by mgarciaferreiro**
Still need to fix constraints

image

### CODE REVIEW

**Comment by joshdoman** [comment]
@mgarciaferreiro Did you make the height of the cell shorter? If so, can you post an image here?

**Comment by mgarciaferreiro** [comment]
> @mgarciaferreiro Did you make the height of the cell shorter? If so, can you post an image here?

image

image

I did it to match the spacing of the dining cell and also changed the font to regular for uniformity, but I can change it back if it looks too tight

**Comment by joshdoman** [comment]
Hmm yeah I'm not a huge fan. Personally I thought the original layout was beautiful, and I'd rather change how Dining looks on the home page than change how reservation looks. Also, it seems like you changed the layout for the reservation cell on BOTH the homepage and the reservation page. Is that what you intended?

**Comment by mgarciaferreiro** [comment]
> Hmm yeah I'm not a huge fan. Personally I thought the original layout was beautiful, and I'd rather change how Dining looks on the home page than change how reservation looks. Also, it seems like you changed the layout for the reservation cell on BOTH the homepage and the reservation page. Is that what you intended?

I did, just because I wasn't sure how to change the height of the whole cell just for the homepage. I agree that the original layout looked nicer, so we should change dining for uniformity. Do you think it's better to just change dining in the homepage or also in the dining page? It might be off putting for them to be different

**Comment by joshdoman** [comment]
Great glad we're on the same page. With regards to dining, I'd suggest that we not overwrite the original dining cell and instead create a copy of it that we change, like DiningCellV2 or something. Depending on how it looks, we may or may not want it to be only on the home page. One reason we may keep it only on the homepage is that the homepage uses

**Pull request merged**
