### PR TITLE
Add dining favorites

### PR DESCRIPTION
**Pull request by nikitamounier**
Adding favorite dining venues. Here's how it looks:

https://github.com/pennlabs/penn-mobile-ios/assets/36044205/d0bfe569-9845-4dc9-b682-b0156e1772fb

The dining venue code was already pretty messy, and this doesn't make it any cleaner. But I've had enough interest for this from people I asked that I think there's worth in pushing it now and working on cleaning up the code (TCA??) later.

### CODE REVIEW

**Comment by nikitamounier** [comment]
Forgot to show how a user can add a venue to favorites from inside the detail view:

https://github.com/pennlabs/penn-mobile-ios/assets/36044205/50524256-3ecd-4f6f-bdfa-dc4e5b24ea00

**Review by anli5005 — APPROVED** [review]

**Review by JHawk0224 — APPROVED** [review]
Looks great!

**Comment by george-botros** [comment]
For future update, the home page dining favorites does not update the dining page dining favorites, and vice-versa. 

https://github.com/pennlabs/penn-mobile-ios/assets/78520093/b319534a-2d30-407d-a8e7-126ecbacc53e

**Comment by JHawk0224** [comment]
> For future update, the home page dining favorites does not update the dining page dining favorites, and vice-versa.
> 
>  Simulator.Screen.Recording.-.iPhone.15.Pro.-.2023-10-10.at.11.21.31.mp4

That's a good point, didn't think about that.

**Pull request merged**
