### PR TITLE
-Dinning tap takes user to web view (internal)

### PR DESCRIPTION
**Pull request by benleim**
-Changed the tap action for dinning halls to take user to a webview within navigation stack.

### CODE REVIEW

**Comment by benleim** [comment]
Hey guys, can you review my changes and if you like it type "LGTM".

**Comment by sanieldalib** [comment]
LGTM

**Comment by mgarciaferreiro** [comment]
LGTM

**Comment by joshdoman** [comment]
LGTM!

**Comment by DominicHolmes** [comment]
good job y'all <3

**Pull request merged**
